package: pdf_viewer
version: '1.0.1' 
author: KLXM Crossmedia GmbH
supportpage: https://github.com/KLXM

# Seiten
page:
    title: 'PDF Viewer'
    perm: pdf_viewer[]
    icon: rex-icon fa-plus-square
    subpages:
        main: {title: 'translate:main'}
            
requires:
    redaxo: '^5.1'
    php:
        version: '>=5.6' 
